Fix

diff --git a/.github/workflows/learn-github-actions.yml b/.github/workflows/learn-github-actions.yml
--- a/.github/workflows/learn-github-actions.yml
+++ b/.github/workflows/learn-github-actions.yml
@@ -1,5 +1,4 @@
 name: generate-petstore-client
-run-name: ${{ github.actor }} is learning GitHub Actions
 on:
   push:
     branches:
@@ -13,10 +12,17 @@ jobs:
       - uses: actions/checkout@v3
       - name: Generate ruby-client
         run: make generate-client
-      - name: git diff
-        # diffがない:exit_code=0, diffがある:exit_code=1
-        run: git diff --quiet --exit-code
-        continue-on-error: true
       - name: Detect diff
-        run: echo 'Diff found'
-        if: ${{ failure() }}
+        run: |
+          if ! git diff --quiet; then
+            echo 'diff found'
+          else
+            ehoc 'diff not found'
+          fi
+      # - name: git diff
+      #   # diffがない:exit_code=0, diffがある:exit_code=1
+      #   run: git diff --quiet --exit-code
+      #   continue-on-error: true
+      # - name: Detect diff
+      #   run: echo 'Diff found'
+      #   if: ${{ failure() }}
